<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Hugo Batista da Silva" />


<title>Evaluation of the Efficacy of Using Growth Hormone Therapy in the Treatment of Children with Idiopathic Short Stature and Small for Gestational Age</title>

<script src="site_libs/header-attrs-2.27/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">MyDataPortfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Profile</a>
</li>
<li>
  <a href="project01.html">Project 01</a>
</li>
<li>
  <a href="project02.html">Project 02</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Evaluation of the Efficacy of Using Growth
Hormone Therapy in the Treatment of Children with Idiopathic Short
Stature and Small for Gestational Age</h1>
<h4 class="author">Hugo Batista da Silva</h4>

</div>


<div id="about-the-project" class="section level2">
<h2>About the project</h2>
<p>The client for this project approached me with a request to analyze
data from the SUS (Unified Health System) to support her master’s thesis
in pharmacy. Due to the pandemic and personal challenges, this project
had been put on hold for two years, necessitating the hiring of a data
scientist.</p>
<p>The data pertain to a growth hormone injection treatment provided by
the government for children with idiopathic short stature (ISS) and
those small for gestational age (SGA). The treatment involves
administering four injections over four years (one per year), with the
child’s height being measured and compared to the average height
expected for their age, as defined by the World Health Organization
(WHO).</p>
<p>The initial goal was to replicate the data on height evolution
according to the injections using official WHO data. However, despite
being a census study, the cohort for the study was small. Consequently,
after conducting descriptive analyses and studies, a linear regression
model was developed using two created indicators.</p>
<p>The final conclusions were not included in this document, as this
study also served as a basis for potential changes in hormone treatment
policy. The purpose of this document is to present the exploratory
analysis and outline how the studies were defined.</p>
</div>
<div id="the-dataset" class="section level2">
<h2>The dataset</h2>
<p>The raw database contains 22 variables; however, after analysis, 8 of
these will be used. The variables included in the analysis are sex,
diagnosis (ISS or SGA), age at the beginning of treatment, height at the
beginning of treatment, height after 1 year of treatment, height after 2
years of treatment, height after 3 years of treatment, and height after
4 years of treatment. The height data is represented as a Z-score,
indicating the deviation from each child’s ideal height (with 0 being
the ideal Z-score). This calculation was performed using WHO
software.</p>
<pre class="r"><code>library(data.table)
library(readxl)

dataset &lt;- as.data.table(read_excel(&quot;PLANILHA.xlsx&quot;))
dataset &lt;- dataset[, c(&quot;SEXO&quot;, &quot;ID_DIAG&quot;, &quot;IDADE_INÍCIO&quot;, &quot;HAZ_INÍCIO&quot;,
                        &quot;HAZ_1ANOS&quot;, &quot;HAZ_2ANOS&quot;, &quot;HAZ_3ANOS&quot;, &quot;HAZ_4ANOS&quot;)]
tail(dataset)</code></pre>
<pre><code>##     SEXO ID_DIAG IDADE_INÍCIO HAZ_INÍCIO HAZ_1ANOS HAZ_2ANOS HAZ_3ANOS
##    &lt;num&gt;  &lt;char&gt;        &lt;num&gt;      &lt;num&gt;     &lt;num&gt;     &lt;num&gt;     &lt;num&gt;
## 1:     1     BEI          145      -1.63     -0.65      0.03        NA
## 2:     0     PIG           99      -2.90     -1.94     -1.74        NA
## 3:     1     BEI           58      -1.39     -0.09      0.05      0.04
## 4:     1     BEI          137      -1.24     -0.02        NA        NA
## 5:     1     PIG          170      -2.24     -1.84        NA        NA
## 6:     0     BEI          136      -3.14     -2.63     -2.12     -1.93
##    HAZ_4ANOS
##        &lt;num&gt;
## 1:        NA
## 2:        NA
## 3:        NA
## 4:        NA
## 5:        NA
## 6:        NA</code></pre>
<p>We have 237 children in the dataset, but as we can see, some of the
children did not complete the entire treatment, but all of them at least
received the first dose of the hormone.</p>
<p>Table of variables:</p>
<pre class="table"><code>| Variable     | Description                                 |
|--------------|---------------------------------------------|
| SEXO         | Sex; (1) male, (0) female                   |
| ID_DIAG      | Diagnosis; BEI, PIG (ISS and SGA)           |
| IDADE_INÍCIO | Age in mounths at start of treatment        |
| HAZ_INÍCIO   | Height in zscore at the start of treatment  |
| HAZ_1ANOS    | Height in zscore after 1 year of treatment  |
| HAZ_2ANOS    | Height in zscore after 2 years of treatment |
| HAZ_3ANOS    | Height in zscore after 3 years of treatment |
| HAZ_4ANOS    | Height in zscore after 4 years of treatment |</code></pre>
</div>
<div id="data-descriptions-graphs-and-tests" class="section level2">
<h2>Data descriptions, Graphs and Tests</h2>
<p>Before starting the descriptive analysis, it was necessary to create
categorical variables for gender and age. Due to the absence of an
explanatory variable for the regression model, two additional indicator
variables were created: “treatment” (tratamento) and “difference”
(diferenca).</p>
<p>The “difference” variable was created to serve as the response
variable in the regression model. This variable represents the
difference between the child’s initial height, recorded before the start
of treatment, and the most recent height available after the start of
treatment.</p>
<p>The “treatment” variable was assigned discrete values of 1, 2, 3, and
4, where “1” represents the completion of a single treatment cycle, “2”
denotes the completion of two cycles, and so on up to “4”. Including the
“treatment” variable as a covariate in the final model allowed us to
investigate the relationship between the patients’ height evolution and
their adherence to the treatment regimen.</p>
<pre class="r"><code>dataset[
  , `:=`(
    sexo_cat = ifelse(SEXO == 1, &quot;Male&quot;, &quot;Female&quot;),
    grupo_idade_t0 = fcase(
      IDADE_INÍCIO &gt;= 0 &amp; IDADE_INÍCIO &lt; 72, &quot;0-71&quot;,
      IDADE_INÍCIO &gt;= 72 &amp; IDADE_INÍCIO &lt; 120, &quot;72-119&quot;,
      IDADE_INÍCIO &gt;= 120, &quot;120+&quot;
    ),
    tratamento = fcase(
      !is.na(HAZ_4ANOS),                                       4,
      !is.na(HAZ_3ANOS) &amp; is.na(HAZ_4ANOS),                    3,
      !is.na(HAZ_2ANOS) &amp; is.na(HAZ_3ANOS) &amp; is.na(HAZ_4ANOS), 2,
      is.na(HAZ_2ANOS) &amp; is.na(HAZ_3ANOS) &amp; is.na(HAZ_4ANOS),  1
    )
  )][,     
     diferenca := fcase(
       tratamento == 1, HAZ_1ANOS - `HAZ_INÍCIO`,
       tratamento == 2, HAZ_2ANOS - `HAZ_INÍCIO`,
       tratamento == 3, HAZ_3ANOS - `HAZ_INÍCIO`,
       tratamento == 4, HAZ_4ANOS - `HAZ_INÍCIO`
     )]</code></pre>
<pre class="r"><code>#A quick analysis of the difference variable, which will be the explanatory variable of the regression model in the future
summary(dataset$diferenca)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  -0.240   0.740   1.120   1.175   1.570   2.830</code></pre>
<pre class="r"><code>boxplot(dataset$diferenca)</code></pre>
<p><img src="project01_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>We observe that the “difference” variable includes negative values,
indicating that some children experienced a decrease in height during
treatment. However, most of the data points are above 0, and both the
median and mean are positive, suggesting that the majority of children
achieved a height greater than expected after treatment.</p>
<p>To make this document more dynamic and concise, we will focus on
analyzing the average evolution of children’s height over the years of
treatment using categorical variables and relevant graphs, leaving out
tabular frequency analyses. Each graph will be followed by a brief
analysis.</p>
<div id="evolution-graphs" class="section level3">
<h3>Evolution Graphs</h3>
<p>For the age variable, we will conduct two analyses: one measuring the
average height and the other measuring the average difference from the
initial height. This approach will allow us to observe the real
evolution in each age group.</p>
<div id="age-average-height" class="section level4">
<h4>Age (average height)</h4>
<pre class="r"><code>dataset_aux &lt;- copy(dataset)
dataset_aux &lt;- dataset_aux[
  ,
  .(
    media0 = mean(HAZ_INÍCIO, na.rm = TRUE),
    media1 = mean(HAZ_1ANOS, na.rm = TRUE),
    media2 = mean(HAZ_2ANOS, na.rm = TRUE),
    media3 = mean(HAZ_3ANOS, na.rm = TRUE),
    media4 = mean(HAZ_4ANOS, na.rm = TRUE)
  ),
  by = .(grupo_idade_t0)
]
dataset_aux &lt;- melt(dataset_aux, na.rm = FALSE, value.name = &quot;media&quot;, id = &quot;grupo_idade_t0&quot;)
dataset_aux[, aux := fcase(
  variable == &quot;media0&quot;, 0,
  variable == &quot;media1&quot;, 1,
  variable == &quot;media2&quot;, 2,
  variable == &quot;media3&quot;, 3,
  variable == &quot;media4&quot;, 4
)]

library(ggplot2)
ggplot(dataset_aux, aes(x = aux, y = media, colour = grupo_idade_t0)) +
  geom_line(linewidth = 1) + 
  theme(legend.text = element_text(size = 15), legend.title = element_text(size = 20), text = element_text(size = 20)) +
  labs(title = &quot;Average height in each year of treatment&quot;,
       y = &quot;Height Z-score&quot;,
       x = &quot;Year of treatment&quot;) +
  guides(color = guide_legend(title = &quot;Age t(0)&quot;))</code></pre>
<p><img src="project01_files/figure-html/unnamed-chunk-4-1.png" width="1344" /></p>
</div>
<div id="age-average-difference-height" class="section level4">
<h4>Age (average difference height)</h4>
<pre class="r"><code>dataset_aux &lt;- copy(dataset)
dataset_aux &lt;- dataset_aux[
  ,
  .(
    media1 = mean(HAZ_1ANOS - HAZ_INÍCIO, na.rm = TRUE),
    media2 = mean(HAZ_2ANOS - HAZ_INÍCIO, na.rm = TRUE),
    media3 = mean(HAZ_3ANOS - HAZ_INÍCIO, na.rm = TRUE),
    media4 = mean(HAZ_4ANOS - HAZ_INÍCIO, na.rm = TRUE)
  ),
  by = .(grupo_idade_t0)
]
dataset_aux &lt;- melt(dataset_aux, na.rm = FALSE, value.name = &quot;media&quot;, id = &quot;grupo_idade_t0&quot;)
dataset_aux[, aux := fcase(
  variable == &quot;media1&quot;, 1,
  variable == &quot;media2&quot;, 2,
  variable == &quot;media3&quot;, 3,
  variable == &quot;media4&quot;, 4
)]

library(ggplot2)
ggplot(dataset_aux, aes(x = aux, y = media, colour = grupo_idade_t0)) +
  geom_line(linewidth = 1) + 
  theme(legend.text = element_text(size = 15), legend.title = element_text(size = 20), text = element_text(size = 20)) +
  labs(title = &quot;Average height difference with initial height in each year of treatment&quot;,
       y = &quot;Height Z-score&quot;,
       x = &quot;Year of treatment&quot;) +
  guides(color = guide_legend(title = &quot;Age t(0)&quot;))</code></pre>
<p><img src="project01_files/figure-html/unnamed-chunk-5-1.png" width="1344" />
Simply using the height graph does not reveal which age group had the
greatest adherence to the treatment. By analyzing the “difference”
variable, we observe that the group aged 0 to 71 months shows a better
difference and evolution compared to the initial stage of treatment.</p>
</div>
<div id="sex-average-height" class="section level4">
<h4>Sex (average height)</h4>
<pre class="r"><code>dataset_aux &lt;- copy(dataset)
dataset_aux &lt;- dataset_aux[
  ,
  .(
    media0 = mean(HAZ_INÍCIO, na.rm = TRUE),
    media1 = mean(HAZ_1ANOS, na.rm = TRUE),
    media2 = mean(HAZ_2ANOS, na.rm = TRUE),
    media3 = mean(HAZ_3ANOS, na.rm = TRUE),
    media4 = mean(HAZ_4ANOS, na.rm = TRUE)
  ),
  by = .(sexo_cat)
]
dataset_aux &lt;- melt(dataset_aux, na.rm = FALSE, value.name = &quot;media&quot;, id = &quot;sexo_cat&quot;)
dataset_aux[, aux := fcase(
  variable == &quot;media0&quot;, 0,
  variable == &quot;media1&quot;, 1,
  variable == &quot;media2&quot;, 2,
  variable == &quot;media3&quot;, 3,
  variable == &quot;media4&quot;, 4
)]

library(ggplot2)
ggplot(dataset_aux, aes(x = aux, y = media, colour = sexo_cat)) +
  geom_line(linewidth = 1) + 
  theme(legend.text = element_text(size = 15), legend.title = element_text(size = 20), text = element_text(size = 20)) +
  labs(title = &quot;Average height in each year of treatment&quot;,
       y = &quot;Height Z-score&quot;,
       x = &quot;Year of treatment&quot;) +
  guides(color = guide_legend(title = &quot;Sex&quot;))</code></pre>
<p><img src="project01_files/figure-html/unnamed-chunk-6-1.png" width="1344" />
We observed that both sexes had similar average initial heights, but
males showed a better response after 1 year of treatment.</p>
</div>
<div id="diagnosis-average-height" class="section level4">
<h4>Diagnosis (average height)</h4>
<pre class="r"><code>dataset_aux &lt;- copy(dataset)
dataset_aux &lt;- dataset_aux[
  ,
  .(
    media0 = mean(HAZ_INÍCIO, na.rm = TRUE),
    media1 = mean(HAZ_1ANOS, na.rm = TRUE),
    media2 = mean(HAZ_2ANOS, na.rm = TRUE),
    media3 = mean(HAZ_3ANOS, na.rm = TRUE),
    media4 = mean(HAZ_4ANOS, na.rm = TRUE)
  ),
  by = .(ID_DIAG)
]
dataset_aux &lt;- melt(dataset_aux, na.rm = FALSE, value.name = &quot;media&quot;, id = &quot;ID_DIAG&quot;)
dataset_aux[, aux := fcase(
  variable == &quot;media0&quot;, 0,
  variable == &quot;media1&quot;, 1,
  variable == &quot;media2&quot;, 2,
  variable == &quot;media3&quot;, 3,
  variable == &quot;media4&quot;, 4
)]

library(ggplot2)
ggplot(dataset_aux, aes(x = aux, y = media, colour = ID_DIAG)) +
  geom_line(linewidth = 1) + 
  theme(legend.text = element_text(size = 15), legend.title = element_text(size = 20), text = element_text(size = 20)) +
  labs(title = &quot;Average height in each year of treatment&quot;,
       y = &quot;Height Z-score&quot;,
       x = &quot;Year of treatment&quot;) +
  guides(color = guide_legend(title = &quot;Diagnosis&quot;))</code></pre>
<p><img src="project01_files/figure-html/unnamed-chunk-7-1.png" width="1344" />
We observed that children diagnosed with BEI initially had better
values, but both BEI and PIG groups showed similar evolution
patterns.</p>
<p>A separate analysis was conducted for the treatment variable, where
we examined its relationship with the average initial height at the
beginning of treatment.</p>
</div>
<div id="treatments-average-initial-height" class="section level4">
<h4>Treatments (average initial height)</h4>
<pre class="r"><code>dataset_aux &lt;- copy(dataset)
dataset_aux &lt;- dataset_aux[
  ,
  .(
    media = mean(HAZ_INÍCIO, na.rm = TRUE)
  ),
  by = .(tratamento)
]

ggplot(dataset_aux, aes(x = tratamento, y = media)) +
  geom_line(linewidth = 1) + 
  theme(legend.text = element_text(size = 15), legend.title = element_text(size = 20), text = element_text(size = 20)) +
  labs(title = &quot;Average initial height per number of treatments&quot;,
       y = &quot;Initial height Z-score&quot;,
       x = &quot;Number of treatments&quot;)</code></pre>
<p><img src="project01_files/figure-html/unnamed-chunk-8-1.png" width="960" />
The analysis of this graph reveals that, interestingly, children with
better initial height values tended to continue the treatment for a
longer duration.</p>
<p>We observed that across all evolution graphs, the difference in
height during the first year is the most significant. Consequently, the
next graph will present a boxplot comparing initial height with height
after 1 year of treatment.</p>
</div>
<div id="boxplot" class="section level4">
<h4>Boxplot</h4>
<pre class="r"><code>#Age group
dataset_aux &lt;- copy(dataset)
dataset_aux1 &lt;- dataset_aux[, c(&quot;HAZ_INÍCIO&quot;, &quot;grupo_idade_t0&quot;)][, cor := &quot;blue&quot;]
dataset_aux2 &lt;- dataset_aux[, c(&quot;HAZ_1ANOS&quot;, &quot;grupo_idade_t0&quot;)][, cor := &quot;red&quot;]
dataset_aux2[, grupo_idade_t0 := fcase(
  grupo_idade_t0 == &quot;0-71&quot;, &quot;0-71 &quot;,
  grupo_idade_t0 == &quot;72-119&quot;, &quot;72-119 &quot;,
  grupo_idade_t0 == &quot;120+&quot;, &quot;120+ &quot;
)]
names(dataset_aux1) &lt;- c(&quot;variavel&quot;, &quot;grupo_idade_t0&quot;, &quot;cor&quot;)
names(dataset_aux2) &lt;- c(&quot;variavel&quot;, &quot;grupo_idade_t0&quot;, &quot;cor&quot;)

dataset_aux3 &lt;- rbind(dataset_aux1, dataset_aux2)
dataset_aux3[, grupo_idade_t0 := 
               factor(grupo_idade_t0,
                      levels = c(&quot;0-71&quot;, &quot;0-71 &quot;, &quot;72-119&quot;, &quot;72-119 &quot;, &quot;120+&quot;, &quot;120+ &quot;))]

b1 &lt;- ggplot(data = dataset_aux3, aes(x = grupo_idade_t0, y = variavel, color = cor)) +
  geom_boxplot() +
  scale_color_identity() +
  labs(y = &#39;Height Z-score&#39;, 
       x = &quot;Age&quot;,
       title = &quot;Initial height (blue) X height after one year of treatment (red)&quot;) +
  scale_y_reverse()

#SEX
dataset_aux1 &lt;- dataset_aux[, c(&quot;HAZ_INÍCIO&quot;, &quot;sexo_cat&quot;)][, cor := &quot;blue&quot;]
dataset_aux2 &lt;- dataset_aux[, c(&quot;HAZ_1ANOS&quot;, &quot;sexo_cat&quot;)][, cor := &quot;red&quot;]
dataset_aux2[, sexo_cat := fcase(
  sexo_cat == &quot;Male&quot;, &quot;Male &quot;,
  sexo_cat == &quot;Female&quot;, &quot;Female &quot;
)]
names(dataset_aux1) &lt;- c(&quot;variavel&quot;, &quot;sexo_cat&quot;, &quot;cor&quot;)
names(dataset_aux2) &lt;- c(&quot;variavel&quot;, &quot;sexo_cat&quot;, &quot;cor&quot;)

dataset_aux3 &lt;- rbind(dataset_aux1, dataset_aux2)
dataset_aux3[, sexo_cat := 
               factor(sexo_cat,
                      levels = c(&quot;Male&quot;, &quot;Male &quot;, &quot;Female&quot;, &quot;Female &quot;))]

b2 &lt;- ggplot(data = dataset_aux3, aes(x = sexo_cat, y = variavel, color = cor)) +
  geom_boxplot() +
  scale_color_identity() +
  labs(y = &#39;Height Z-score&#39;, 
       x = &quot;Sex&quot;,
       title = &quot;Initial height (blue) X height after one year of treatment (red)&quot;) +
  scale_y_reverse()

#TREATMENT
dataset_aux1 &lt;- dataset_aux[, c(&quot;HAZ_INÍCIO&quot;, &quot;tratamento&quot;)][, cor := &quot;blue&quot;][, tratamento := as.character(tratamento)]
dataset_aux1[, tratamento := fcase(tratamento == &quot;1&quot;, &quot;T1&quot;, tratamento == &quot;2&quot;, &quot;T2&quot;, tratamento == &quot;3&quot;, &quot;T3&quot;, tratamento == &quot;4&quot;, &quot;T4&quot;)]
dataset_aux2 &lt;- dataset_aux[, c(&quot;HAZ_1ANOS&quot;, &quot;tratamento&quot;)][, cor := &quot;red&quot;][, tratamento := as.character(tratamento)]
dataset_aux2[, tratamento := fcase(tratamento == &quot;1&quot;, &quot;T1&quot;, tratamento == &quot;2&quot;, &quot;T2&quot;, tratamento == &quot;3&quot;, &quot;T3&quot;, tratamento == &quot;4&quot;, &quot;T4&quot;)]
dataset_aux2[, tratamento := fcase(
  tratamento == &quot;T1&quot;, &quot;T1 &quot;,
  tratamento == &quot;T2&quot;, &quot;T2 &quot;,
  tratamento == &quot;T3&quot;, &quot;T3 &quot;,
  tratamento == &quot;T4&quot;, &quot;T4 &quot;
)]
names(dataset_aux1) &lt;- c(&quot;variavel&quot;, &quot;tratamento&quot;, &quot;cor&quot;)
names(dataset_aux2) &lt;- c(&quot;variavel&quot;, &quot;tratamento&quot;, &quot;cor&quot;)

dataset_aux3 &lt;- rbind(dataset_aux1, dataset_aux2)
dataset_aux3[, tratamento := 
               factor(tratamento,
                      levels = c(&quot;T1&quot;, &quot;T1 &quot;, &quot;T2&quot;, &quot;T2 &quot;,&quot;T3&quot;, &quot;T3 &quot;,&quot;T4&quot;, &quot;T4 &quot;))]

b3 &lt;- ggplot(data = dataset_aux3, aes(x = tratamento, y = variavel, color = cor)) +
  geom_boxplot() +
  scale_color_identity() +
  labs(y = &#39;Height Z-score&#39;, 
       x = &quot;Years of Treatment&quot;,
       title = &quot;Initial height (blue) X height after one year of treatment (red)&quot;) +
  scale_y_reverse()

#DIAGNOSIS
dataset_aux1 &lt;- dataset_aux[, c(&quot;HAZ_INÍCIO&quot;, &quot;ID_DIAG&quot;)][, cor := &quot;blue&quot;]
dataset_aux2 &lt;- dataset_aux[, c(&quot;HAZ_1ANOS&quot;, &quot;ID_DIAG&quot;)][, cor := &quot;red&quot;]
dataset_aux2[, ID_DIAG := fcase(
  ID_DIAG == &quot;BEI&quot;, &quot;BEI &quot;,
  ID_DIAG == &quot;PIG&quot;, &quot;PIG &quot;
)]
names(dataset_aux1) &lt;- c(&quot;variavel&quot;, &quot;ID_DIAG&quot;, &quot;cor&quot;)
names(dataset_aux2) &lt;- c(&quot;variavel&quot;, &quot;ID_DIAG&quot;, &quot;cor&quot;)

dataset_aux3 &lt;- rbind(dataset_aux1, dataset_aux2)
dataset_aux3[, ID_DIAG := 
               factor(ID_DIAG,
                      levels = c(&quot;BEI&quot;, &quot;BEI &quot;,&quot;PIG&quot;, &quot;PIG &quot;))]

b4 &lt;- ggplot(data = dataset_aux3, aes(x = ID_DIAG, y = variavel, color = cor)) +
  geom_boxplot() +
  scale_color_identity() +
  labs(y = &#39;Height Z-score&#39;, 
       x = &quot;Diagnosis&quot;,
       title = &quot;Initial height (blue) X height after one year of treatment (red)&quot;) +
  scale_y_reverse()

library(gridExtra)
grid.arrange(b1, b2, b3, b4, ncol = 2)</code></pre>
<p><img src="project01_files/figure-html/unnamed-chunk-9-1.png" width="1344" /></p>
<pre class="r"><code>#Cleaning the environment
rm(dataset_aux, dataset_aux1, dataset_aux2, dataset_aux3, b1, b2, b3, b4)
invisible(gc())</code></pre>
<p>We observed that the age group 0 to 71 months showed the most
significant improvement. Regarding sex, differences were not evident in
the boxplots. In terms of treatment duration, children who underwent 4
years of treatment exhibited the greatest initial difference in the
first year. For diagnosis differences were not evident.</p>
</div>
</div>
<div id="tests" class="section level3">
<h3>Tests</h3>
<p>To assess whether the average heights are significantly different
after one year of treatment, we will conduct paired t-tests for each
boxplot. However, before applying the test, one of the assumptions is
that the data (z-score heights) are normally distributed. To confirm the
normality of the data, we will conduct four different normality tests.
The paired t-test involves the following hypotheses:</p>
<p><span class="math inline">\(H_0 =\)</span> The means of the two
groups are equal.</p>
<p><span class="math inline">\(H_1 =\)</span> The means of the two
groups are different.</p>
<p>For the normality tests below the hypotheses are:</p>
<p><span class="math inline">\(H_0 =\)</span> The data follows a normal
distribution.</p>
<p><span class="math inline">\(H_1 =\)</span> The data does not follow a
normal distribution.</p>
<div id="normality-test" class="section level4">
<h4>Normality Test</h4>
<pre class="r"><code>haz_in &lt;- dataset$HAZ_INÍCIO
haz_1 &lt;- dataset$HAZ_1ANOS
test &lt;- cbind(haz_in, haz_1)

library(nortest)
t1 &lt;- ks.test(test,&quot;pnorm&quot;, mean=mean(test), sd=sd(test)) # KS
t2 &lt;- lillie.test(test) # Lilliefors
t3 &lt;- cvm.test(test) # Cramer-von Mises
t4 &lt;- ad.test(test) # Anderson-Darling

# Result Table
testes &lt;- c(t1$method, t2$method, t3$method, t4$method)
estt &lt;- as.numeric(c(t1$statistic, t2$statistic, t3$statistic, t4$statistic))
pvalue &lt;- c(t1$p.value, t2$p.value, t3$p.value, t4$p.value)
results &lt;- cbind(estt, pvalue)
rownames(results) &lt;- testes
colnames(results) &lt;- c(&quot;Statistics&quot;, &quot;p-value&quot;)
print(results, digits = 4)</code></pre>
<pre><code>##                                                Statistics p-value
## Asymptotic one-sample Kolmogorov-Smirnov test     0.03472  0.6172
## Lilliefors (Kolmogorov-Smirnov) normality test    0.03472  0.1787
## Cramer-von Mises normality test                   0.07979  0.2080
## Anderson-Darling normality test                   0.54168  0.1636</code></pre>
<p>All tests indicate that there is insufficient evidence to reject the
null hypothesis that the data follow a normal distribution. Therefore,
based on these results, we can conclude that the data meet the
assumption of normality.</p>
</div>
<div id="t-test-for-the-age" class="section level4">
<h4>T-Test for the Age</h4>
<pre class="r"><code>t071 &lt;- t.test(dataset[grupo_idade_t0 == &quot;0-71&quot;, &quot;HAZ_INÍCIO&quot;], 
               dataset[grupo_idade_t0 == &quot;0-71&quot;, &quot;HAZ_1ANOS&quot;])
t72119 &lt;- t.test(dataset[grupo_idade_t0 == &quot;72-119&quot;, &quot;HAZ_INÍCIO&quot;], 
                 dataset[grupo_idade_t0 == &quot;72-119&quot;, &quot;HAZ_1ANOS&quot;])
t120 &lt;- t.test(dataset[grupo_idade_t0 == &quot;120+&quot;, &quot;HAZ_INÍCIO&quot;], 
               dataset[grupo_idade_t0 == &quot;120+&quot;, &quot;HAZ_1ANOS&quot;])

group &lt;- c(&quot;0 to 71&quot;, &quot;72 to 119&quot;, &quot;120+&quot;)
ci1 &lt;- as.numeric(c(t071$conf.int[1], t72119$conf.int[1], t120$conf.int[1]))
ci2 &lt;- as.numeric(c(t071$conf.int[2], t72119$conf.int[2], t120$conf.int[2]))
pvalue &lt;- c(t071$p.value, t72119$p.value, t120$p.value)
results &lt;- cbind(ci1, ci2, pvalue)
rownames(results) &lt;- paste0(&quot;t-test age &quot;, group)
colnames(results) &lt;- c(&quot;ci_lower&quot;, &quot;ci_upper&quot;, &quot;p-value&quot;)
print(results, digits = 4)</code></pre>
<pre><code>##                      ci_lower ci_upper   p-value
## t-test age 0 to 71    -1.2860  -0.7747 8.582e-13
## t-test age 72 to 119  -0.9820  -0.5369 3.273e-10
## t-test age 120+       -0.8752  -0.3934 5.174e-07</code></pre>
</div>
<div id="t-test-for-the-sex" class="section level4">
<h4>T-Test for the Sex</h4>
<pre class="r"><code>male &lt;- t.test(dataset[sexo_cat == &quot;Male&quot;, &quot;HAZ_INÍCIO&quot;], 
               dataset[sexo_cat == &quot;Male&quot;, &quot;HAZ_1ANOS&quot;])
female &lt;- t.test(dataset[sexo_cat == &quot;Female&quot;, &quot;HAZ_INÍCIO&quot;], 
                 dataset[sexo_cat == &quot;Female&quot;, &quot;HAZ_1ANOS&quot;])

group &lt;- c(&quot;male&quot;, &quot;female&quot;)
ci1 &lt;- as.numeric(c(male$conf.int[1], female$conf.int[1]))
ci2 &lt;- as.numeric(c(male$conf.int[2], female$conf.int[2]))
pvalue &lt;- c(male$p.value, female$p.value)
results &lt;- cbind(ci1, ci2, pvalue)
rownames(results) &lt;- paste0(&quot;t-test for &quot;, group)
colnames(results) &lt;- c(&quot;ci_lower&quot;, &quot;ci_upper&quot;, &quot;p-value&quot;)
print(results, digits = 4)</code></pre>
<pre><code>##                   ci_lower ci_upper   p-value
## t-test for male    -1.0415  -0.6633 9.457e-17
## t-test for female  -0.8901  -0.4642 2.239e-09</code></pre>
</div>
<div id="t-test-for-the-diagnosis" class="section level4">
<h4>T-Test for the Diagnosis</h4>
<pre class="r"><code>bei &lt;- t.test(dataset[ID_DIAG == &quot;BEI&quot;, &quot;HAZ_INÍCIO&quot;], 
              dataset[ID_DIAG == &quot;BEI&quot;, &quot;HAZ_1ANOS&quot;])
pig &lt;- t.test(dataset[ID_DIAG == &quot;PIG&quot;, &quot;HAZ_INÍCIO&quot;], 
              dataset[ID_DIAG == &quot;PIG&quot;, &quot;HAZ_1ANOS&quot;])

group &lt;- c(&quot;bei&quot;, &quot;pig&quot;)
ci1 &lt;- as.numeric(c(bei$conf.int[1], pig$conf.int[1]))
ci2 &lt;- as.numeric(c(bei$conf.int[2], pig$conf.int[2]))
pvalue &lt;- c(bei$p.value, pig$p.value)
results &lt;- cbind(ci1, ci2, pvalue)
rownames(results) &lt;- paste0(&quot;t-test for &quot;, group)
colnames(results) &lt;- c(&quot;ci_lower&quot;, &quot;ci_upper&quot;, &quot;p-value&quot;)
print(results, digits = 4)</code></pre>
<pre><code>##                ci_lower ci_upper   p-value
## t-test for bei  -0.9743  -0.6076 1.248e-15
## t-test for pig  -0.9633  -0.5612 2.633e-12</code></pre>
</div>
<div id="t-test-for-the-years-of-treatment" class="section level4">
<h4>T-Test for the Years of Treatment</h4>
<pre class="r"><code>t1 &lt;- t.test(dataset[tratamento == 1, &quot;HAZ_INÍCIO&quot;], 
             dataset[tratamento == 1, &quot;HAZ_1ANOS&quot;])
t2 &lt;- t.test(dataset[tratamento == 2, &quot;HAZ_INÍCIO&quot;], 
             dataset[tratamento == 2, &quot;HAZ_1ANOS&quot;])
t3 &lt;- t.test(dataset[tratamento == 3, &quot;HAZ_INÍCIO&quot;], 
             dataset[tratamento == 3, &quot;HAZ_1ANOS&quot;])
t4 &lt;- t.test(dataset[tratamento == 4, &quot;HAZ_INÍCIO&quot;], 
             dataset[tratamento == 4, &quot;HAZ_1ANOS&quot;])

group &lt;- c(&quot;1yrs treatment&quot;, &quot;2yrs treatment&quot;, &quot;3yrs treatment&quot;, &quot;4yrs treatment&quot;)
ci1 &lt;- as.numeric(c(t1$conf.int[1], t2$conf.int[1], t3$conf.int[1], t4$conf.int[1]))
ci2 &lt;- as.numeric(c(t1$conf.int[2], t2$conf.int[2], t3$conf.int[2], t4$conf.int[2]))
pvalue &lt;- c(t1$p.value, t2$p.value, t3$p.value, t4$p.value)
results &lt;- cbind(ci1, ci2, pvalue)
rownames(results) &lt;- paste0(&quot;t-test for &quot;, group)
colnames(results) &lt;- c(&quot;ci_lower&quot;, &quot;ci_upper&quot;, &quot;p-value&quot;)
print(results, digits = 4)</code></pre>
<pre><code>##                           ci_lower ci_upper   p-value
## t-test for 1yrs treatment  -1.0347  -0.4453 2.187e-06
## t-test for 2yrs treatment  -0.9955  -0.4916 4.413e-08
## t-test for 3yrs treatment  -0.9920  -0.4014 8.152e-06
## t-test for 4yrs treatment  -1.1978  -0.7110 5.478e-12</code></pre>
<p>We observe that for all variable groups, the confidence intervals of
the tests do not contain zero, indicating a significant difference
between the mean heights at the beginning and after 1 year of treatment.
The p-values for all groups are extremely small, suggesting a
statistically significant difference and indicating a significant
increase in height across all groups. Particularly, the age group 0 to
71 months had the lowest p-value among the age groups, and this trend
applies similarly to males, those with a BEI diagnosis, and those who
underwent 4 years of treatment.</p>
<pre class="r"><code>#Cleaning the environment
rm(results, pvalue, ci2, ci1, group, t4, t3, t2, t1, pig, bei, female, 
   male, t120, t72119, t071, estt, testes, test, haz_1, haz_in)
invisible(gc())</code></pre>
</div>
</div>
</div>
<div id="modeling" class="section level2">
<h2>Modeling</h2>
<p>After the descriptive analyses, graphs and tests, we will move on to
the second part of this project, which is modeling. I’ll be brief so
this page doesn’t get too big (it’s already huge).</p>
<p>After carrying out tests with all variables and interactions between
them, the final model was defined as:</p>
<div id="regression-model" class="section level3">
<h3>Regression Model</h3>
<pre class="r"><code>#To help interpret the model, the variable age in months was transformed into age in years.
dataset[, `IDADE_INÍCIO` := `IDADE_INÍCIO`/12]
fit &lt;- lm(diferenca ~ tratamento + HAZ_INÍCIO + `IDADE_INÍCIO` + SEXO + ID_DIAG, data = dataset)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = diferenca ~ tratamento + HAZ_INÍCIO + IDADE_INÍCIO + 
##     SEXO + ID_DIAG, data = dataset)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.13986 -0.30675 -0.01432  0.30083  1.54778 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   0.477699   0.176087   2.713  0.00717 ** 
## tratamento    0.254714   0.030810   8.267 1.08e-14 ***
## HAZ_INÍCIO   -0.197996   0.040437  -4.896 1.83e-06 ***
## IDADE_INÍCIO -0.042164   0.009691  -4.351 2.04e-05 ***
## SEXO          0.242183   0.059417   4.076 6.30e-05 ***
## ID_DIAGPIG   -0.149874   0.064551  -2.322  0.02111 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4455 on 231 degrees of freedom
## Multiple R-squared:  0.4383, Adjusted R-squared:  0.4261 
## F-statistic: 36.05 on 5 and 231 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In the model above, all coefficients are significant at the 95%
confidence level. The coefficient of determination, R², is a crucial
measure of model quality, indicating the proportion of variability in
the response variable explained by the independent variables. Here, R²
is 0.4261, suggesting that approximately 42.61% of the variability in
the ‘difference’ variable is explained by the included independent
variables.</p>
<p>While 42.61% may seem relatively low, it’s important to note that the
data are in z-scores, which inherently limit variability. When the model
was tested using height variables in centimeters, an R² greater than 0.8
was achieved. However, z-scores were chosen to standardize the evolution
of child height and avoid large differences between groups.</p>
<p>Additionally, the residual standard error is low at 0.4455, and the
F-statistic has an extremely low p-value, indicating that the model
significantly outperforms a model without predictors.</p>
<pre class="r"><code># The confidence interval of the coefficients
confint(fit)</code></pre>
<pre><code>##                    2.5 %      97.5 %
## (Intercept)   0.13075686  0.82464063
## tratamento    0.19400957  0.31541844
## HAZ_INÍCIO   -0.27766744 -0.11832377
## IDADE_INÍCIO -0.06125781 -0.02307043
## SEXO          0.12511481  0.35925185
## ID_DIAGPIG   -0.27705743 -0.02269063</code></pre>
<p>The 95% confidence intervals for the coefficient estimates are
reliable, as none of them include the number 0. This indicates that
these predictors robustly explain the variation in the dependent
variable.</p>
<p>Now, to confirm the veracity of the chosen model, we will study the
assumptions necessary for its validation.</p>
<div id="multicollinearity" class="section level4">
<h4>Multicollinearity</h4>
<pre class="r"><code>car::vif(fit)</code></pre>
<pre><code>##   tratamento   HAZ_INÍCIO IDADE_INÍCIO         SEXO      ID_DIAG 
##     1.397790     1.154201     1.392548     1.025447     1.203038</code></pre>
<p>The VIF (Variance Inflation Factor) results indicate the extent to
which the variance of a regression coefficient is inflated due to
collinearity with other independent variables in the model. For a model
to be acceptable, the VIF should be less than 5. As observed, all
variables have a VIF below 2, confirming that there is no significant
multicollinearity among the predictor variables in this model.</p>
</div>
<div id="points-of-influenceleverageoutliers" class="section level4">
<h4>Points of influence/leverage/outliers</h4>
<pre class="r"><code># Number of observations
n &lt;- nrow(dataset)

#Number of coeficients
k &lt;- length(fit$coef)   

#Leverage cut
corte.hii&lt;- 2*k/n   
#Cookis distance cut
corte.cook&lt;- 4/n

par(mfrow = c(2, 1))

plot(hatvalues(fit), type = &quot;h&quot;, cex.lab = 1.5, cex.axis = 1.5,
     xlab = &quot;Observation&quot;, ylab = &quot;Leverage&quot;,
     ylim = c(0, max(max(hatvalues(fit)), corte.hii)))
lines(c(0, n + 1), c(corte.hii, corte.hii), col = &#39;red&#39;, lty = 2)

plot(fit, which = 4)
lines(c(0, n + 1), c(corte.cook, corte.cook), col = &#39;red&#39;, lty = 2)</code></pre>
<p><img src="project01_files/figure-html/unnamed-chunk-19-1.png" width="1344" /></p>
<pre class="r"><code># Higher Leverages
hatv &lt;- order(hatvalues(fit),decreasing=TRUE)[1:10]
hatv</code></pre>
<pre><code>##  [1] 225  80  10  66   1  45  94  44 219  84</code></pre>
<pre class="r"><code># Higher Cooks Distance
cooks &lt;- order(cooks.distance(fit),decreasing=TRUE)[1:10]   
cooks</code></pre>
<pre><code>##  [1] 225  10 166  54 130  34 193  93 203  83</code></pre>
<pre class="r"><code>#Higher leveragens and cook distance at the same time
critic_points &lt;- Reduce(intersect, list(hatv, cooks))
critic_points</code></pre>
<pre><code>## [1] 225  10</code></pre>
<p>We can see that among the 10 largest leverage and cook distance
points, only 2 coexist in both groups. The recommended option is to
remove these points, but after running the model without these two
points, the best difference between them was the increase in R² to
0.4313. Therefore, it was decided to keep the 2 points in the model,
considering that the data is reliable and they are probably legitimate
outliers.</p>
<p>Now continuing the verification of the model assumptions we have.</p>
</div>
<div id="residual-analysis" class="section level4">
<h4>Residual Analysis</h4>
<pre class="r"><code>#Standardized Residuals
sr&lt;- rstandard(fit)
par(mfrow = c(1, 2))

plot(sr, pch = 20, cex.lab = 1.5, cex.axis = 1.5, 
     xlab = &quot;Observation&quot;, ylab = &quot;Standardized Residuals&quot;,
     ylim = c(min(-2, min(sr)), max(2, max(sr))))
lines(c(0, n + 1), c(2, 2), col = &#39;red&#39;, lty = 2)
lines(c(0, n + 1), c(-2, -2), col = &#39;red&#39;, lty = 2)
high_residuals &lt;- which(abs(sr) &gt; 2)
points(high_residuals, sr[high_residuals], col = &quot;red&quot;, pch = 20)
text(high_residuals, sr[high_residuals], labels = round(sr[high_residuals], 2),
     pos = 3, col = &quot;red&quot;, cex = 0.7)

boxplot(sr, pch = 20, cex.lab = 1.5, cex.axis = 1.5, xlab = &quot;Standardized Residuals&quot;)</code></pre>
<p><img src="project01_files/figure-html/unnamed-chunk-20-1.png" width="1344" />
The residuals are evenly distributed around 0, as observed in the
boxplot where the median is very close to 0, and the distribution is
well-balanced. There are only 10 points outside the range of -2 to 2,
indicating very good residual values.</p>
<p>Next, we will perform a normality test to finalize the residual
analysis.</p>
<pre class="r"><code>t1 &lt;- ks.test(sr,&quot;pnorm&quot;) # KS
t2 &lt;- lillie.test(sr) # Lilliefors
t3 &lt;- cvm.test(sr) # Cramer-von Mises
t4 &lt;- shapiro.test(sr) # Shapiro-Wilk
t5 &lt;- sf.test(sr) # Shapiro-Francia
t6 &lt;- ad.test(sr) # Anderson-Darling
# Tabela de resultados
testes &lt;- c(t1$method, t2$method, t3$method, t4$method, t5$method, t6$method)
estt &lt;- as.numeric(c(t1$statistic, t2$statistic, t3$statistic, t4$statistic, t5$statistic, t6$statistic))
valorp &lt;- c(t1$p.value, t2$p.value, t3$p.value, t4$p.value, t5$p.value, t6$p.value)
resultados &lt;- cbind(estt, valorp)
rownames(resultados) &lt;- testes
colnames(resultados) &lt;- c(&quot;Statistic&quot;, &quot;p-value&quot;)
print(resultados, digits = 4)</code></pre>
<pre><code>##                                                Statistic p-value
## Asymptotic one-sample Kolmogorov-Smirnov test    0.02766  0.9935
## Lilliefors (Kolmogorov-Smirnov) normality test   0.02716  0.9401
## Cramer-von Mises normality test                  0.02177  0.9504
## Shapiro-Wilk normality test                      0.99578  0.7664
## Shapiro-Francia normality test                   0.99511  0.5689
## Anderson-Darling normality test                  0.16817  0.9355</code></pre>
<p>All six tests indicate that there is insufficient evidence to reject
the null hypothesis that the residuals follow a normal distribution.
Therefore, we conclude that the residuals meet the assumption of
normality.</p>
</div>
<div id="homoscedasticity" class="section level4">
<h4>Homoscedasticity</h4>
<pre class="r"><code># Breusch-Pagan Test
lmtest::bptest(fit) </code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 4.4489, df = 5, p-value = 0.4868</code></pre>
<p>The absence of heteroscedasticity in the residuals is crucial as it
ensures that confidence intervals and significance tests of the
regression model coefficients are correctly interpreted. With a p-value
of 0.4868, there is no statistically significant evidence to reject the
null hypothesis of the test indicating no heteroscedasticity in the
model residuals. Therefore, we conclude that the residuals exhibit
homoscedasticity.</p>
</div>
<div id="conclusion" class="section level4">
<h4>Conclusion</h4>
<p>After confirming all assumptions and validating the model, we are now
ready to interpret the coefficients and infer the model. The final model
is as follows:</p>
<p><span class="math display">\[Y = 0.4777 + 0.2547X_1 - 0.198X_2 -
0.0422X_3 + 0.2422X_4 - 0.1499X_5\]</span></p>
<table>
<colgroup>
<col width="8%" />
<col width="92%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Y</td>
<td>Difference between the child’s initial height and the most recent
height available after the start of treatment.</td>
</tr>
<tr class="even">
<td>X1</td>
<td>Number of treatments</td>
</tr>
<tr class="odd">
<td>X2</td>
<td>Height in zscore at the start of treatment</td>
</tr>
<tr class="even">
<td>X3</td>
<td>Age in years at the start of treatment</td>
</tr>
<tr class="odd">
<td>X4</td>
<td>Sex (male)</td>
</tr>
<tr class="even">
<td>X5</td>
<td>Diagnosis (PIG)</td>
</tr>
</tbody>
</table>
<p>We observe that the intercept value indicates that the height
difference will be 0.4777, meaning the child will grow by 0.477 in
z-score, regardless of the other variables.</p>
<p>The “number of treatments” variable has the most significant impact
on this difference. Each year of hormone treatment results in an
increase of 0.2547 in the difference, which can reach up to 1.0188.</p>
<p>For the “initial height” variable, we interpret that the more
negative the z-score, the greater the difference at the end of the
treatment. In other words, the shorter the initial height of the child,
the greater the final difference, with a coefficient of -0.198.</p>
<p>The “age” variable works similarly to initial height, but it always
“worsens” the difference since age is always positive and the
coefficient is negative. We conclude that the younger the child, the
better the final difference, as the difference will be greater.</p>
<p>Regarding sex, we find that boys respond better to the treatment.
Being male increases the difference by 0.2422, while for girls, this
difference decreases by 0.2422.</p>
<p>Finally, children diagnosed as SGA (Small for Gestational Age) show a
slight worsening in the difference, while those diagnosed as ISS
(Idiopathic Short Stature) show an improvement.</p>
<p>We conclude that the ideal scenario for a child to achieve the best
results is to complete the 4 years of treatment, have the lowest
possible initial height z-score, start treatment at the youngest age, be
male, and be diagnosed as ISS.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
